-- Spelling Bee — Extra Word List (8+ letters, obscurity 2–4)
-- 120 new words, no duplicates with seed.sql or morewords.sql

INSERT INTO words (spelling, definition, variant, length, obscurity) VALUES

-- === OBSURITY 2 ===

('accommodation', 'A place to stay or live temporarily', 'both', 13, 2),
('anecdote', 'A short amusing or interesting story about a real incident', 'both', 8, 2),
('benevolent', 'Well-meaning and kindly in nature', 'both', 10, 2),
('catalyst', 'A substance that increases the rate of a chemical reaction', 'both', 8, 2),
('clarification', 'The act of making a statement or situation less confused', 'both', 13, 2),
('crescendo', 'A gradual increase in the intensity of something', 'both', 9, 2),
('discrepancy', 'A lack of compatibility between facts or claims', 'both', 11, 2),
('innocuous', 'Not harmful or offensive in any way', 'both', 9, 2),
('inundate', 'To overwhelm with a great quantity of something', 'both', 8, 2),
('quandary', 'A state of perplexity or uncertainty about what to do', 'both', 8, 2),
('requisite', 'Made necessary by particular circumstances', 'both', 9, 2),
('reticent', 'Not revealing one''s thoughts or feelings readily', 'both', 8, 2),
('rhetorical', 'Relating to the art of persuasive speaking or writing', 'both', 10, 2),
('semblance', 'The outward appearance or apparent form of something', 'both', 9, 2),
('succinct', 'Briefly and clearly expressed', 'both', 8, 2),
('unprecedented', 'Never done or known before', 'both', 13, 2),
('vivacious', 'Attractively lively and animated', 'both', 9, 2),
('extravagant', 'Lacking restraint in spending money or resources', 'both', 11, 2),
('nonchalant', 'Feeling calm and relaxed; not worried', 'both', 10, 2),
('egregious', 'Outstandingly bad; shocking', 'both', 9, 2),

-- === OBScurity 3 ===

('acquiescence', 'Reluctant acceptance without protest', 'both', 12, 3),
('altercation', 'A noisy argument or disagreement', 'both', 11, 3),
('amalgamate', 'To combine or unite to form one entity', 'both', 10, 3),
('ambivalence', 'The state of having mixed feelings about something', 'both', 11, 3),
('antecedent', 'A thing that existed or came before another', 'both', 10, 3),
('apparatus', 'Equipment or machinery for a particular purpose', 'both', 9, 3),
('calibrate', 'To mark an instrument with a standard scale of values', 'both', 9, 3),
('cavalcade', 'A procession of people on horseback or in vehicles', 'both', 9, 3),
('circumscribe', 'To restrict or limit something within boundaries', 'both', 12, 3),
('commensurate', 'Corresponding in size, extent, or degree', 'both', 12, 3),
('compendium', 'A collection of detailed information about a subject', 'both', 10, 3),
('confluence', 'A place where two rivers or streams flow together', 'both', 10, 3),
('conjecture', 'An opinion formed without sufficient evidence', 'both', 10, 3),
('contiguous', 'Sharing a common border or touching', 'both', 10, 3),
('corroborate', 'To confirm or give support to a statement or theory', 'both', 11, 3),
('culminate', 'To reach a climax or point of highest development', 'both', 9, 3),
('deplorable', 'Deserving strong condemnation or disapproval', 'both', 10, 3),
('derogatory', 'Showing a critical or disrespectful attitude', 'both', 10, 3),
('disconcert', 'To make someone feel unsettled or uneasy', 'both', 10, 3),
('disseminate', 'To spread information or knowledge widely', 'both', 11, 3),
('dissident', 'A person who opposes official policy or doctrine', 'both', 9, 3),
('dogmatic', 'Inclined to lay down principles as undeniably true', 'both', 8, 3),
('effervescent', 'Vivacious and enthusiastic in personality', 'both', 12, 3),
('efficacious', 'Successful in producing a desired result', 'both', 11, 3),
('elucidate', 'To make something clear by explaining it', 'both', 9, 3),
('enigmatic', 'Difficult to interpret or understand; mysterious', 'both', 9, 3),
('enumerate', 'To mention things or numbers one by one', 'both', 9, 3),
('ephemeral', 'Lasting for a very short time; transient', 'both', 9, 3),
('equanimity', 'Mental calmness and composure in a difficult situation', 'both', 10, 3),
('equivocal', 'Open to more than one interpretation; ambiguous', 'both', 9, 3),
('exacerbate', 'To make a problem or situation worse', 'both', 10, 3),
('expediency', 'The quality of being convenient rather than correct', 'both', 10, 3),
('fastidious', 'Very attentive to and concerned about accuracy and detail', 'both', 10, 3),
('magnanimous', 'Very generous or forgiving, especially to a rival', 'both', 11, 3),
('mellifluous', 'Sweet-sounding and pleasant to hear', 'both', 11, 3),
('mercurial', 'Subject to sudden or unpredictable changes of mood', 'both', 9, 3),
('nebulous', 'Vague, unclear, or ill-defined', 'both', 8, 3),
('nonplussed', 'So surprised or confused as to be unsure how to react', 'both', 10, 3),
('ostensible', 'Appearing as such but not necessarily so', 'both', 10, 3),
('pandemonium', 'Wild and noisy disorder or confusion', 'both', 11, 3),
('parochial', 'Having a limited or narrow outlook or scope', 'both', 9, 3),
('pastiche', 'An artistic work that imitates the style of another', 'both', 8, 3),
('sanguine', 'Optimistic or positive about the future', 'both', 8, 3),
('soliloquy', 'The act of speaking one''s thoughts aloud when alone', 'both', 9, 3),
('somnolent', 'Sleepy or drowsy; inducing sleep', 'both', 9, 3),
('specious', 'Superficially plausible but actually wrong', 'both', 8, 3),
('trepidation', 'A feeling of fear or agitation about something', 'both', 11, 3),
('ubiquitous', 'Present, appearing, or found everywhere', 'both', 10, 3),
('unequivocal', 'Leaving no doubt; unambiguous', 'both', 11, 3),
('vacillate', 'To be indecisive; to waver between opinions', 'both', 9, 3),
('vehement', 'Showing strong and passionate feelings', 'both', 8, 3),
('vicarious', 'Experienced through the feelings of another person', 'both', 9, 3),
('voluminous', 'Occupying or containing a great deal of space', 'both', 10, 3),
('voracious', 'Wanting or devouring great quantities', 'both', 9, 3),
('fallacious', 'Based on a mistaken belief or unsound argument', 'both', 10, 3),
('fortuitous', 'Happening by accident or chance rather than design', 'both', 10, 3),
('haphazard', 'Lacking any obvious principle of organization', 'both', 9, 3),
('immutable', 'Unchanging over time or unable to be changed', 'both', 9, 3),
('convoluted', 'Extremely complex and difficult to follow', 'both', 10, 3),

-- === OBScurity 4 ===

('ameliorate', 'To make something bad or unsatisfactory better', 'both', 10, 4),
('audacious', 'Showing a willingness to take surprisingly bold risks', 'both', 9, 4),
('bifurcation', 'Division into two branches or parts', 'both', 11, 4),
('blandishment', 'A flattering statement used to persuade someone', 'both', 12, 4),
('brazenness', 'Bold and without shame or embarrassment', 'both', 10, 4),
('circuitous', 'Longer than the most direct way or route', 'both', 10, 4),
('concatenate', 'To link things together in a chain or series', 'both', 11, 4),
('contravene', 'To violate or act against a rule or treaty', 'both', 10, 4),
('deprecate', 'To express disapproval of something', 'both', 9, 4),
('desultory', 'Lacking a plan, purpose, or enthusiasm', 'both', 9, 4),
('dilatory', 'Slow to act or intended to cause delay', 'both', 8, 4),
('emaciated', 'Abnormally thin and weak from illness or hunger', 'both', 9, 4),
('emancipate', 'To set free from legal or social restrictions', 'both', 10, 4),
('encomium', 'A formal expression of high praise', 'both', 8, 4),
('erstwhile', 'Former; previous', 'both', 9, 4),
('exculpate', 'To prove that someone is not guilty of wrongdoing', 'both', 9, 4),
('extemporaneous', 'Spoken or done without preparation', 'both', 14, 4),
('felicitous', 'Well chosen or suited to the circumstances', 'both', 10, 4),
('harbinger', 'A person or thing that signals the approach of another', 'both', 9, 4),
('iconoclast', 'A person who attacks cherished beliefs or institutions', 'both', 10, 4),
('ignominious', 'Deserving or causing public disgrace or shame', 'both', 11, 4),
('imperturbable', 'Unable to be upset, excited, or annoyed', 'both', 13, 4),
('implacable', 'Unable to be placated or appeased', 'both', 10, 4),
('inexorable', 'Impossible to stop or prevent', 'both', 10, 4),
('inveterate', 'Having a habit or interest that is long-established', 'both', 10, 4),
('licentious', 'Not restrained by moral principles', 'both', 10, 4),
('lucubration', 'Laborious study or writing, especially at night', 'both', 11, 4),
('mendacious', 'Not telling the truth; lying', 'both', 10, 4),
('obdurate', 'Stubbornly refusing to change one''s opinion', 'both', 8, 4),
('obsequious', 'Excessively obedient or attentive to someone', 'both', 10, 4),
('parsimonious', 'Unwilling to spend money; extremely frugal', 'both', 12, 4),
('pejorative', 'Expressing contempt or disapproval', 'both', 10, 4),
('penchant', 'A strong or habitual liking for something', 'both', 8, 4),
('penurious', 'Extremely poor; poverty-stricken', 'both', 9, 4),
('perfunctory', 'Carried out with minimum effort or reflection', 'both', 11, 4),
('petulant', 'Childishly sulky or bad-tempered', 'both', 8, 4),
('garrulous', 'Excessively talkative about trivial matters', 'both', 9, 4),
('defamatory', 'Intended to damage the reputation of someone', 'both', 10, 4),
('patrician', 'A person of refined and cultivated taste', 'both', 9, 4),
('brouhaha', 'A noisy and overexcited reaction or response', 'both', 8, 4),
('disabuse', 'To persuade someone that a belief is mistaken', 'both', 8, 4);
