-- Spelling Bee — Unified Word Seed File
-- Total: 477 words

INSERT INTO words (spelling, definition, variant, length, obscurity) VALUES
('garden', 'A piece of ground used for growing flowers, fruit, or vegetables', 'both', 6, 1),
('branch', 'A part of a tree that grows out from the trunk', 'both', 6, 1),
('planet', 'A celestial body orbiting a star', 'both', 6, 1),
('bridge', 'A structure carrying a road, path, or railway over a river or obstacle', 'both', 6, 1),
('hammer', 'A tool with a heavy metal head used for striking', 'both', 6, 1),
('kitchen', 'A room where food is prepared and cooked', 'both', 7, 1),
('island', 'A piece of land surrounded by water', 'both', 6, 1),
('forest', 'A large area covered chiefly with trees', 'both', 6, 1),
('butter', 'A dairy product made by churning cream', 'both', 6, 1),
('museum', 'A building housing historical or artistic collections', 'both', 6, 1),
('bizarre', 'Very strange or unusual', 'both', 7, 2),
('solemn', 'Formal and dignified; not cheerful', 'both', 6, 2),
('vanish', 'Disappear suddenly and completely', 'both', 6, 2),
('ancient', 'Belonging to the very distant past', 'both', 7, 2),
('harbour', 'A sheltered place for ships (British spelling)', 'british', 7, 2),
('harbor', 'A sheltered place for ships (American spelling)', 'american', 6, 2),
('dolphin', 'A marine mammal with a streamlined body', 'both', 7, 2),
('gnawed', 'Bite at or chew something persistently', 'both', 6, 3),
('lacquer', 'A liquid coating that dries to a hard shiny finish', 'both', 7, 3),
('thwart', 'To prevent someone from accomplishing something', 'both', 6, 3),
('camouflage', 'Disguise that blends with the surrounding environment', 'both', 10, 3),
('conscience', 'An inner feeling of right and wrong', 'both', 10, 3),
('brochure', 'A small booklet containing information about a product or service', 'both', 8, 3),
('colour', 'The property of objects that produces different sensations on the eye', 'british', 6, 3),
('color', 'The property of objects that produces different sensations on the eye', 'american', 5, 3),
('theatre', 'A building for dramatic performances (British spelling)', 'british', 7, 3),
('theater', 'A building for dramatic performances (American spelling)', 'american', 7, 3),
('silhouette', 'A dark image or outline against a light background', 'both', 10, 4),
('embarrass', 'To cause someone to feel awkward or ashamed', 'both', 9, 4),
('privilege', 'A special right or advantage', 'both', 9, 4),
('sacrilege', 'Violation of something sacred', 'both', 9, 4),
('realise', 'To become fully aware of something (British spelling)', 'british', 7, 4),
('realize', 'To become fully aware of something (American spelling)', 'american', 7, 4),
('favour', 'An act of kindness beyond what is due (British spelling)', 'british', 6, 4),
('favor', 'An act of kindness beyond what is due (American spelling)', 'american', 5, 4),
('pharaoh', 'An ancient Egyptian ruler', 'both', 7, 5),
('rhythm', 'A repeated pattern of movement or sound', 'both', 6, 5),
('bureaucracy', 'A system of government with many levels of officials', 'both', 11, 5),
('idiosyncrasy', 'A mode of behaviour or way of thought peculiar to an individual', 'both', 12, 5),
('onomatopoeia', 'A word that imitates the sound it describes', 'both', 12, 5),
('centre', 'The middle point of something (British spelling)', 'british', 6, 5),
('center', 'The middle point of something (American spelling)', 'american', 6, 5),
('defence', 'The action of defending against attack (British spelling)', 'british', 7, 5),
('defense', 'The action of defending against attack (American spelling)', 'american', 7, 5),
('absolutely', 'Completely or without any doubt', 'both', 10, 1),
('argument', 'A disagreement or the process of disagreeing', 'both', 8, 1),
('achievement', 'Something very good and difficult that you have succeeded in doing', 'both', 11, 1),
('explanation', 'The details or reasons given to make something clear', 'both', 11, 1),
('jealous', 'Upset and angry because someone you love seems interested in someone else', 'both', 7, 1),
('technique', 'A way of doing an activity that needs skill', 'both', 9, 1),
('admission', 'The money that you pay to enter a place', 'both', 9, 1),
('breathe', 'To move air into and out of the lungs', 'both', 7, 1),
('convenient', 'Suitable for your purposes and needs, causing the least difficulty', 'both', 10, 1),
('definitely', 'Without any doubt', 'both', 10, 1),
('disappear', 'To go somewhere where you cannot be seen or found', 'both', 9, 1),
('gorgeous', 'Very beautiful or pleasant', 'both', 8, 1),
('ingredient', 'A food that is used with other foods in the preparation of a dish', 'both', 10, 1),
('kangaroo', 'A large Australian mammal with long powerful back legs for jumping', 'both', 8, 1),
('length', 'The measurement of something from end to end', 'both', 6, 1),
('league', 'A group of teams competing against each other in a sport', 'both', 6, 1),
('magnificent', 'Very good, beautiful, or deserving to be admired', 'both', 11, 1),
('permanent', 'Lasting for a long time or forever', 'both', 9, 1),
('queue', 'A line of people waiting for something', 'both', 5, 1),
('routine', 'A usual or fixed way of doing things', 'both', 7, 1),
('security', 'Protection against threats such as crime or attack', 'both', 8, 1),
('serious', 'Severe in effect; bad', 'both', 7, 1),
('wander', 'To walk around slowly without any clear purpose or direction', 'both', 6, 1),
('warmth', 'A comfortable but not hot temperature', 'both', 6, 1),
('vinegar', 'A sharp-tasting liquid used to add flavour to or preserve food', 'both', 7, 1),
('illegal', 'Not allowed by law', 'both', 7, 1),
('youth', 'The period of your life when you are young', 'both', 5, 1),
('width', 'The distance across something from one side to the other', 'both', 5, 1),
('parade', 'A large number of people walking together in a public celebration', 'both', 6, 1),
('laundry', 'Dirty clothes that need to be, are being, or have been washed', 'both', 7, 1),
('occasionally', 'Sometimes but not often', 'both', 12, 1),
('volunteer', 'A person who helps willingly without being forced or paid', 'both', 9, 1),
('wound', 'A damaged area of the body, such as a cut or hole made by a weapon', 'both', 5, 1),
('decade', 'A period of ten years', 'both', 6, 1),
('nonsense', 'Silly or stupid behaviour, ideas, or speech', 'both', 8, 1),
('pattern', 'A particular way in which something is done or happens', 'both', 7, 1),
('strength', 'The ability to do things that need a lot of physical or mental effort', 'both', 8, 1),
('nuisance', 'Something or someone that annoys you or causes trouble', 'both', 8, 1),
('lobby', 'The large room into which the main entrance door opens in a hotel or building', 'both', 5, 1),
('definite', 'Fixed, certain, or clear', 'both', 8, 1),
('graduate', 'A person who has a first degree from a university or college', 'both', 8, 1),
('collapse', 'To fall down suddenly because of pressure or lack of strength', 'both', 8, 1),
('poisonous', 'Very harmful and able to cause illness or death', 'both', 9, 1),
('precious', 'Of great value because of being rare, expensive, or important', 'both', 8, 1),
('atmosphere', 'The mixture of gases around the earth', 'both', 10, 1),
('furious', 'Extremely angry', 'both', 7, 1),
('feature', 'A typical quality or an important part of something', 'both', 7, 1),
('cease', 'To stop something', 'both', 5, 1),
('hilarious', 'Extremely funny and causing a lot of laughter', 'both', 9, 1),
('filthy', 'Extremely or unpleasantly dirty', 'both', 6, 1),
('numerous', 'Many', 'both', 8, 1),
('lounge', 'A room in a house used for relaxing and entertaining guests', 'both', 6, 1),
('awareness', 'Knowledge that something exists or understanding of a situation', 'both', 9, 1),
('official', 'Relating to a position of responsibility', 'both', 8, 1),
('toddler', 'A young child who is learning or has recently learned to walk', 'both', 7, 1),
('beige', 'A pale brown colour', 'both', 5, 1),
('unpleasant', 'Rude and angry; not enjoyable or agreeable', 'both', 10, 1),
('groan', 'A deep, long sound showing great pain or unhappiness', 'both', 5, 1),
('janitor', 'A person employed to take care of a large building', 'both', 7, 1),
('fiction', 'A type of literature that describes imaginary events and people', 'both', 7, 1),
('loosen', 'To become loose', 'both', 6, 1),
('ballet', 'A type of dancing with carefully organised movements that tell a story', 'both', 6, 2),
('entertainment', 'Shows, films, or other performances that entertain people', 'both', 13, 2),
('expedition', 'An organised journey for a particular purpose', 'both', 10, 2),
('literature', 'Written artistic works with high and lasting artistic value', 'both', 10, 2),
('pharmacy', 'A shop or part of a shop in which medicines are prepared and sold', 'both', 8, 2),
('pedestrian', 'A person who is walking, especially in an area where vehicles go', 'both', 10, 2),
('astronaut', 'A person trained for travelling in space', 'both', 9, 2),
('architecture', 'The style in which buildings are made', 'both', 12, 2),
('certificate', 'An official document stating that the information on it is true', 'both', 11, 2),
('competitor', 'A person, team, or company that is competing against others', 'both', 10, 2),
('exhibition', 'An event where paintings or other objects are shown to the public', 'both', 10, 2),
('gymnastics', 'Physical exercises intended to increase the body''s strength and flexibility', 'both', 10, 2),
('heroine', 'A woman admired for having done something very brave or great', 'both', 7, 2),
('laboratory', 'A room with scientific equipment for doing tests or teaching science', 'both', 10, 2),
('marvellous', 'Extremely good', 'british', 10, 2),
('registration', 'The act of recording a name or information on an official list', 'both', 12, 2),
('maintenance', 'The work needed to keep a road, building, or machine in good condition', 'both', 11, 2),
('variation', 'A change in amount or level', 'both', 9, 2),
('yacht', 'A boat with sails, used for racing or travelling for pleasure', 'both', 5, 2),
('comedian', 'A person whose job is to make people laugh by telling jokes', 'both', 8, 2),
('criticism', 'The act of saying that something or someone is bad', 'both', 9, 2),
('reception', 'A formal party at which important people are welcomed', 'both', 9, 2),
('schedule', 'A list of planned activities showing when they are intended to happen', 'both', 8, 2),
('territory', 'An area of land belonging to or connected with a particular country', 'both', 9, 2),
('ultimate', 'Most extreme or important; the original, final, best, or worst', 'both', 8, 2),
('virtually', 'Almost', 'both', 9, 2),
('vividly', 'In a way that is very clear, powerful, and detailed in your mind', 'both', 7, 2),
('quarrel', 'An angry disagreement between two or more people or groups', 'both', 7, 2),
('journalism', 'The work of collecting and publishing news in newspapers or on television', 'both', 10, 2),
('theory', 'A formal set of ideas intended to explain a fact or event', 'both', 6, 2),
('voyage', 'A long journey, especially by ship', 'both', 6, 2),
('significant', 'Important or noticeable', 'both', 11, 2),
('recreation', 'A way of enjoying yourself when you are not working', 'both', 10, 2),
('haunt', 'To cause repeated suffering or anxiety', 'both', 5, 2),
('tragedy', 'A very sad event involving death or suffering', 'both', 7, 2),
('referee', 'A person who makes sure the rules are followed in a sports game', 'both', 7, 2),
('query', 'A question expressing doubt or looking for an answer', 'both', 5, 2),
('offence', 'An illegal act; a crime', 'both', 7, 2),
('genuine', 'Real and exactly what it appears to be', 'both', 7, 2),
('admiration', 'The feeling of admiring someone or something', 'both', 10, 2),
('barrier', 'A fence, wall, or natural feature that stops people from going somewhere', 'both', 7, 2),
('refugee', 'A person who has escaped from their country for political or safety reasons', 'both', 7, 2),
('tremendous', 'Very great in amount or level, or extremely good', 'both', 10, 2),
('regional', 'Relating to or coming from a particular part of a country', 'both', 8, 2),
('peculiar', 'Unusual and strange, sometimes in an unpleasant way', 'both', 8, 2),
('finance', 'A supply of money', 'both', 7, 2),
('enthusiasm', 'A feeling of energetic interest in a particular subject', 'both', 10, 2),
('typically', 'In a way that shows all the expected characteristics', 'both', 9, 2),
('independent', 'Not influenced or controlled by other people or things', 'both', 11, 2),
('anxiety', 'An uncomfortable feeling of nervousness or worry about the future', 'both', 7, 2),
('deliberate', 'Intentional or planned', 'both', 10, 2),
('appropriate', 'Suitable or right for a particular situation or occasion', 'both', 11, 2),
('monument', 'A building built to honour a special person or event', 'both', 8, 2),
('potential', 'Possible when the necessary conditions exist', 'both', 9, 2),
('committee', 'A small group chosen to represent a larger organisation', 'both', 9, 2),
('association', 'A group of people who work together for a particular purpose', 'both', 11, 2),
('guarantee', 'A promise that something will be done or will happen', 'both', 9, 2),
('authority', 'The moral or legal right or ability to control', 'both', 9, 2),
('curiosity', 'An eager wish to know or learn about something', 'both', 9, 2),
('lyrics', 'The words of a song', 'both', 6, 2),
('butler', 'The most important male servant in a house', 'both', 6, 2),
('guardian', 'A person who has the legal right to take care of someone', 'both', 8, 2),
('attendant', 'Someone whose job is to be in a place and help visitors or customers', 'both', 9, 2),
('bulletin', 'A short news programme on television or radio', 'both', 8, 2),
('exert', 'To use authority, power, or influence to make something happen', 'both', 5, 2),
('mousse', 'A light cold food made from eggs mixed with cream', 'both', 6, 2),
('lullaby', 'A quiet song sung to children to help them go to sleep', 'both', 7, 2),
('grudge', 'A strong feeling of anger for someone who has treated you badly', 'both', 6, 2),
('hurricane', 'A violent wind with a circular movement, especially in the Atlantic', 'both', 9, 2),
('hurdle', 'A frame or fence for jumping over in a race', 'both', 6, 2),
('boycott', 'To refuse to buy a product or take part in an activity as a protest', 'both', 7, 2),
('etiquette', 'The set of rules that control accepted behaviour in social groups', 'both', 9, 2),
('boisterous', 'Noisy, energetic, and rough', 'both', 10, 2),
('columnist', 'Someone who writes a regular article for a newspaper or magazine', 'both', 9, 2),
('monastery', 'A building in which monks live and worship', 'both', 9, 2),
('graffiti', 'Words or drawings on walls or other public places', 'both', 8, 2),
('flammable', 'Something that burns easily', 'both', 9, 2),
('blizzard', 'A severe snow storm with strong winds', 'both', 8, 2),
('blemish', 'A mark on something that spoils its appearance', 'both', 7, 2),
('rhythmic', 'Having a regular movement or beat that is repeated', 'both', 8, 2),
('pilgrimage', 'A special journey made by a pilgrim', 'both', 10, 2),
('lodging', 'A temporary place to stay', 'both', 7, 2),
('glutton', 'A person who regularly eats and drinks more than is needed', 'both', 7, 2),
('fixated', 'Unable to stop thinking about something', 'both', 7, 2),
('binge', 'An occasion when an activity is done in an extreme way', 'both', 5, 2),
('glamorous', 'Attractive in an exciting and special way', 'both', 9, 2),
('default', 'To fail to do something that you legally have to do', 'both', 7, 2),
('gadget', 'A small device or machine with a particular purpose', 'both', 6, 2),
('naive', 'Too willing to believe that people are telling the truth', 'both', 5, 2),
('tactic', 'A planned way of doing something', 'both', 6, 2),
('ethnic', 'Relating to a group of people who can be seen as distinct', 'both', 6, 2),
('selective', 'Intentionally choosing some things and not others', 'both', 9, 2),
('obstacle', 'Something that blocks you so that movement is prevented', 'both', 8, 2),
('necessity', 'The need for something', 'both', 9, 2),
('neglect', 'To not give enough care or attention to people or things', 'both', 7, 2),
('debut', 'The first time someone performs or presents something to the public', 'both', 5, 2),
('campaign', 'A planned group of activities intended to achieve a particular aim', 'both', 8, 2),
('bankrupt', 'Unable to pay what you owe', 'both', 8, 2),
('juvenile', 'Relating to a young person not yet old enough to be considered an adult', 'both', 8, 2),
('accordance', 'Following or obeying a rule, law, or wish', 'both', 10, 2),
('mechanism', 'A set of parts that work together in a machine', 'both', 9, 2),
('affluent', 'Having a lot of money or owning a lot of things', 'both', 8, 2),
('personnel', 'The people employed in a company or organisation', 'both', 9, 2),
('superior', 'Better than average or better than others of the same type', 'both', 8, 2),
('philosophy', 'The way that someone thinks about life and deals with it', 'both', 10, 2),
('amateur', 'Taking part in an activity for pleasure, not as a job', 'both', 7, 2),
('nutritious', 'Containing many of the substances needed for life and growth', 'both', 10, 2),
('delegate', 'A person chosen to speak or vote for a group at a meeting', 'both', 8, 2),
('plunge', 'To become lower in value or level very suddenly and quickly', 'both', 6, 2),
('posture', 'The way in which someone holds their shoulders, neck, and back', 'both', 7, 2),
('insufficient', 'Not enough', 'both', 12, 2),
('primitive', 'Relating to a very early stage of development', 'both', 9, 2),
('exhaust', 'To make someone extremely tired', 'both', 7, 2),
('courageous', 'Having or showing courage', 'both', 10, 2),
('luxurious', 'Very comfortable and expensive', 'both', 9, 2),
('drought', 'A long period with little or no rain', 'both', 7, 2),
('irrational', 'Not using reason or clear thinking', 'both', 10, 2),
('consensus', 'A generally accepted opinion among a group of people', 'both', 9, 2),
('fraud', 'The crime of getting money by deceiving people', 'both', 5, 2),
('hygienic', 'Clean, especially in order to prevent disease', 'both', 8, 2),
('initiate', 'To cause something to begin', 'both', 8, 2),
('conceive', 'To imagine something', 'both', 8, 2),
('infinite', 'Without limits; extremely large or great', 'both', 8, 2),
('flourish', 'To grow or develop successfully', 'both', 8, 2),
('incentive', 'Something that encourages a person to do something', 'both', 9, 2),
('hostage', 'Someone taken as a prisoner to force others to do what the enemy wants', 'both', 7, 2),
('ornament', 'An object that is beautiful rather than useful', 'both', 8, 2),
('restriction', 'An official limit on something', 'both', 11, 2),
('orientation', 'Training or preparation for a new job or activity', 'both', 11, 2),
('loathe', 'To hate someone or something', 'both', 6, 2),
('horizon', 'The line where the sky seems to touch the land or sea', 'both', 7, 2),
('ordeal', 'A very unpleasant and painful or difficult experience', 'both', 6, 2),
('resignation', 'The act of telling your employer that you are leaving your job', 'both', 11, 2),
('tribute', 'Something you give that shows respect and admiration', 'both', 7, 2),
('mediocre', 'Not very good', 'both', 8, 2),
('nostalgia', 'A feeling of pleasure and slight sadness when thinking about the past', 'both', 9, 2),
('optimism', 'The quality of being full of hope and emphasising the good parts', 'both', 8, 2),
('pathetic', 'Causing feelings of sadness, sympathy, or sometimes lack of respect', 'both', 8, 2),
('trauma', 'Severe emotional shock and pain caused by an extremely upsetting experience', 'both', 6, 2),
('quotation', 'The price that a person or company says they will charge for work', 'both', 9, 2),
('lenient', 'Not as severe or strong in punishment as would be expected', 'both', 7, 2),
('deceased', 'Dead', 'both', 8, 2),
('adjacent', 'Very near, next to, or touching', 'both', 8, 2),
('casserole', 'A dish of meat and vegetables cooked slowly in liquid in a heavy container', 'both', 9, 2),
('torture', 'The act of causing great physical or mental pain', 'both', 7, 2),
('illusion', 'An idea or belief that is not true', 'both', 8, 2),
('accelerate', 'To increase speed', 'both', 10, 2),
('sequence', 'A series of related things in a particular order', 'both', 8, 2),
('famine', 'A situation where there is not enough food, causing illness and death', 'both', 6, 2),
('fundamental', 'Forming the base from which everything else develops', 'both', 11, 2),
('yearn', 'To wish very strongly for something you cannot have', 'both', 5, 2),
('diarrhea', 'An illness in which solid waste is more liquid than usual and comes out more often', 'both', 8, 2),
('abrupt', 'Sudden and unexpected, often unpleasant', 'both', 6, 2),
('odour', 'A smell, often one that is unpleasant', 'british', 5, 2),
('prescription', 'A piece of paper on which a doctor writes the medicine that someone needs', 'both', 12, 3),
('embarrassment', 'The feeling of being embarrassed', 'both', 13, 3),
('parliament', 'The group of elected politicians who make the laws for their country', 'both', 10, 3),
('hyphen', 'The symbol used to join two words together', 'both', 6, 3),
('intellectual', 'Relating to your ability to think and understand complicated ideas', 'both', 12, 3),
('dilemma', 'A situation in which a difficult choice has to be made', 'both', 7, 3),
('mystique', 'A quality of being special in a mysterious and attractive way', 'both', 8, 3),
('hysteria', 'Extreme fear, excitement, or anger that cannot be controlled', 'both', 8, 3),
('exuberant', 'Very energetic', 'both', 9, 3),
('fugitive', 'A person who is running away from the police or a dangerous situation', 'both', 8, 3),
('myriad', 'A very large number of something', 'both', 6, 3),
('pseudonym', 'A name someone uses instead of their real name on a written work', 'both', 9, 3),
('bunting', 'Rows of small flags hung as decoration for special occasions', 'both', 7, 3),
('foresight', 'The ability to judge what will happen in the future and plan accordingly', 'both', 9, 3),
('luminous', 'Producing or reflecting bright light, especially in the dark', 'both', 8, 3),
('mosaic', 'A pattern or picture made using many small pieces of coloured stone or glass', 'both', 6, 3),
('hydrant', 'A vertical pipe connected to the main water system for supplying water for fires', 'both', 7, 3),
('gruelling', 'Extremely tiring and difficult, demanding great effort and determination', 'british', 9, 3),
('forage', 'To go from place to place searching for things that you can eat or use', 'both', 6, 3),
('desolate', 'Empty and not attractive, with no people or nothing pleasant', 'both', 8, 3),
('foetus', 'A young human or animal before birth, after the organs have started to develop', 'british', 6, 3),
('grotesque', 'Strange and unpleasant, especially in a silly or frightening way', 'both', 9, 3),
('fluoride', 'A chemical substance added to water or toothpaste to help keep teeth healthy', 'both', 8, 3),
('depreciate', 'To lose value, especially over time', 'both', 10, 3),
('ethereal', 'Light and delicate, especially in an unnatural way', 'both', 8, 3),
('grievance', 'A complaint or strong feeling of having been treated unfairly', 'both', 9, 3),
('humungous', 'Extremely large', 'both', 9, 3),
('inevitable', 'Certain to happen and unable to be avoided or prevented', 'both', 10, 3),
('montage', 'A piece of work produced by combining smaller parts', 'both', 7, 3),
('indigenous', 'Originally living in a place, rather than moving there from somewhere else', 'both', 10, 3),
('estuary', 'The wide part of a river where it joins the sea', 'both', 7, 3),
('chutney', 'A mixture of fruit, spices, and vinegar eaten with meat or cheese', 'both', 7, 3),
('defunct', 'No longer existing, living, or working correctly', 'both', 7, 3),
('erroneous', 'Wrong or false', 'both', 9, 3),
('flamboyant', 'Very confident and liking to be noticed by other people', 'both', 10, 3),
('momentous', 'Very important because of effects on future events', 'both', 9, 3),
('pinnacle', 'The most successful or admired part of a system or achievement', 'both', 8, 3),
('superstitious', 'Based on old ideas about luck and magic rather than science or reason', 'both', 13, 3),
('miscellaneous', 'Consisting of a mixture of various things not usually connected', 'both', 13, 3),
('hullabaloo', 'A loud noise made by angry people; a lot of angry public comments', 'both', 10, 3),
('chronology', 'The order in which a series of events happened', 'both', 10, 3),
('benefactor', 'Someone who gives money to help an organisation or person', 'both', 10, 3),
('chronicle', 'To make a record or give details of something', 'both', 9, 3),
('inauspicious', 'Showing signs that something will not be successful or positive', 'both', 12, 3),
('nullify', 'To make a legal agreement or decision have no legal force', 'both', 7, 3),
('turbulence', 'A state of confusion without any order', 'both', 10, 3),
('truancy', 'The problem of children being absent from school regularly without permission', 'both', 7, 3),
('sumptuous', 'Impressive in a way that seems expensive', 'both', 9, 3),
('inaudible', 'Unable to be heard', 'both', 9, 3),
('horrendous', 'Extremely unpleasant or bad', 'both', 10, 3),
('gladiator', 'In ancient Rome, a man who fought another man or animal for entertainment', 'both', 9, 3),
('encryption', 'The process of changing information into a secret code', 'both', 10, 3),
('chiffon', 'A very thin, almost transparent cloth of silk or nylon', 'both', 7, 3),
('obsolete', 'Not in use any more, having been replaced by something newer', 'both', 8, 3),
('occurrence', 'Something that happens', 'both', 10, 3),
('negotiation', 'The process of discussing something to reach an agreement', 'both', 11, 3),
('simultaneous', 'Happening or being done at exactly the same time', 'both', 12, 3),
('descendant', 'A person related to you who lives after you, such as your child or grandchild', 'both', 10, 3),
('lucrative', 'Producing a lot of money', 'both', 9, 3),
('commemorate', 'To remember and give respect to a great person or event with a ceremony', 'both', 11, 3),
('humility', 'The quality of not being proud because you are aware of your bad qualities', 'both', 8, 3),
('anonymous', 'Made or done by someone whose name is not known', 'both', 9, 3),
('humanitarian', 'Involved in improving people''s lives and reducing suffering', 'both', 13, 3),
('longevity', 'Living for a long time', 'both', 9, 3),
('orthodox', 'Considered traditional, normal, and acceptable by most people', 'both', 8, 3),
('ambiguous', 'Having or expressing more than one possible meaning', 'both', 9, 3),
('millennium', 'A period of 1,000 years', 'both', 10, 3),
('revelation', 'The act of making something known that was secret', 'both', 10, 3),
('albeit', 'Although', 'both', 6, 3),
('charisma', 'A special power that makes people able to influence and attract others', 'both', 8, 3),
('hierarchy', 'A system in which people or things are arranged according to importance', 'both', 9, 3),
('lavish', 'Large in quantity and expensive or impressive', 'both', 6, 3),
('reconcile', 'To find a way in which two opposing situations can agree and exist together', 'both', 9, 3),
('discretion', 'The right or ability to decide something', 'both', 10, 3),
('malicious', 'Intended to harm or upset other people', 'both', 9, 3),
('unanimous', 'When everyone in a group agrees about one particular matter', 'both', 9, 3),
('predecessor', 'Someone who had a job or position before someone else', 'both', 11, 3),
('municipal', 'Of or belonging to a town or city', 'both', 9, 3),
('deteriorate', 'To become worse', 'both', 11, 3),
('itinerary', 'A detailed plan or route of a journey', 'both', 9, 3),
('hypocrisy', 'Pretending to believe something that you do not really believe', 'both', 9, 3),
('gumption', 'The ability to decide the best thing to do in a situation and do it with energy', 'both', 8, 4),
('exhilarate', 'To give someone strong feelings of happiness and excitement', 'both', 10, 4),
('guillotine', 'A device with a sharp blade used for killing criminals by cutting off their heads', 'both', 10, 4),
('diaphragm', 'The muscle that separates the chest from the lower part of the body', 'both', 9, 4),
('euthanasia', 'The act of killing someone who is very ill so that they do not suffer any more', 'both', 10, 4),
('archipelago', 'A group of small islands or an area of sea with many small islands', 'both', 11, 4),
('euphemism', 'A word or phrase used to avoid saying an unpleasant or offensive word', 'both', 9, 4),
('influent', 'Water or other liquid that flows into a waste treatment centre', 'both', 8, 4),
('moratorium', 'A stopping of an activity for an agreed amount of time', 'both', 10, 4),
('bougainvillea', 'A climbing plant with red or purple flowers, common in hot countries', 'both', 13, 4),
('loquacious', 'Having the habit of talking a lot', 'both', 10, 4),
('endorphin', 'A chemical released in the brain to reduce pain and create feelings of energy', 'both', 9, 4),
('conscientious', 'Putting a lot of effort into your work', 'both', 13, 4),
('meticulous', 'Very careful and paying great attention to every detail', 'both', 10, 4),
('paradigm', 'A model of something or a very clear and typical example', 'both', 8, 4),
('pyjamas', 'Soft, loose clothing worn in bed, consisting of trousers and a shirt', 'british', 7, 4),
('deficiency', 'A state of not having enough of something that is needed', 'both', 10, 4),
('accommodation', 'A place to stay or live temporarily', 'both', 13, 2),
('anecdote', 'A short amusing or interesting story about a real incident', 'both', 8, 2),
('benevolent', 'Well-meaning and kindly in nature', 'both', 10, 2),
('catalyst', 'A substance that increases the rate of a chemical reaction', 'both', 8, 2),
('clarification', 'The act of making a statement or situation less confused', 'both', 13, 2),
('crescendo', 'A gradual increase in the intensity of something', 'both', 9, 2),
('discrepancy', 'A lack of compatibility between facts or claims', 'both', 11, 2),
('innocuous', 'Not harmful or offensive in any way', 'both', 9, 2),
('inundate', 'To overwhelm with a great quantity of something', 'both', 8, 2),
('quandary', 'A state of perplexity or uncertainty about what to do', 'both', 8, 2),
('requisite', 'Made necessary by particular circumstances', 'both', 9, 2),
('reticent', 'Not revealing one''s thoughts or feelings readily', 'both', 8, 2),
('rhetorical', 'Relating to the art of persuasive speaking or writing', 'both', 10, 2),
('semblance', 'The outward appearance or apparent form of something', 'both', 9, 2),
('succinct', 'Briefly and clearly expressed', 'both', 8, 2),
('unprecedented', 'Never done or known before', 'both', 13, 2),
('vivacious', 'Attractively lively and animated', 'both', 9, 2),
('extravagant', 'Lacking restraint in spending money or resources', 'both', 11, 2),
('nonchalant', 'Feeling calm and relaxed; not worried', 'both', 10, 2),
('egregious', 'Outstandingly bad; shocking', 'both', 9, 2),
('acquiescence', 'Reluctant acceptance without protest', 'both', 12, 3),
('altercation', 'A noisy argument or disagreement', 'both', 11, 3),
('amalgamate', 'To combine or unite to form one entity', 'both', 10, 3),
('ambivalence', 'The state of having mixed feelings about something', 'both', 11, 3),
('antecedent', 'A thing that existed or came before another', 'both', 10, 3),
('apparatus', 'Equipment or machinery for a particular purpose', 'both', 9, 3),
('calibrate', 'To mark an instrument with a standard scale of values', 'both', 9, 3),
('cavalcade', 'A procession of people on horseback or in vehicles', 'both', 9, 3),
('circumscribe', 'To restrict or limit something within boundaries', 'both', 12, 3),
('commensurate', 'Corresponding in size, extent, or degree', 'both', 12, 3),
('compendium', 'A collection of detailed information about a subject', 'both', 10, 3),
('confluence', 'A place where two rivers or streams flow together', 'both', 10, 3),
('conjecture', 'An opinion formed without sufficient evidence', 'both', 10, 3),
('contiguous', 'Sharing a common border or touching', 'both', 10, 3),
('corroborate', 'To confirm or give support to a statement or theory', 'both', 11, 3),
('culminate', 'To reach a climax or point of highest development', 'both', 9, 3),
('deplorable', 'Deserving strong condemnation or disapproval', 'both', 10, 3),
('derogatory', 'Showing a critical or disrespectful attitude', 'both', 10, 3),
('disconcert', 'To make someone feel unsettled or uneasy', 'both', 10, 3),
('disseminate', 'To spread information or knowledge widely', 'both', 11, 3),
('dissident', 'A person who opposes official policy or doctrine', 'both', 9, 3),
('dogmatic', 'Inclined to lay down principles as undeniably true', 'both', 8, 3),
('effervescent', 'Vivacious and enthusiastic in personality', 'both', 12, 3),
('efficacious', 'Successful in producing a desired result', 'both', 11, 3),
('elucidate', 'To make something clear by explaining it', 'both', 9, 3),
('enigmatic', 'Difficult to interpret or understand; mysterious', 'both', 9, 3),
('enumerate', 'To mention things or numbers one by one', 'both', 9, 3),
('ephemeral', 'Lasting for a very short time; transient', 'both', 9, 3),
('equanimity', 'Mental calmness and composure in a difficult situation', 'both', 10, 3),
('equivocal', 'Open to more than one interpretation; ambiguous', 'both', 9, 3),
('exacerbate', 'To make a problem or situation worse', 'both', 10, 3),
('expediency', 'The quality of being convenient rather than correct', 'both', 10, 3),
('fastidious', 'Very attentive to and concerned about accuracy and detail', 'both', 10, 3),
('magnanimous', 'Very generous or forgiving, especially to a rival', 'both', 11, 3),
('mellifluous', 'Sweet-sounding and pleasant to hear', 'both', 11, 3),
('mercurial', 'Subject to sudden or unpredictable changes of mood', 'both', 9, 3),
('nebulous', 'Vague, unclear, or ill-defined', 'both', 8, 3),
('nonplussed', 'So surprised or confused as to be unsure how to react', 'both', 10, 3),
('ostensible', 'Appearing as such but not necessarily so', 'both', 10, 3),
('pandemonium', 'Wild and noisy disorder or confusion', 'both', 11, 3),
('parochial', 'Having a limited or narrow outlook or scope', 'both', 9, 3),
('pastiche', 'An artistic work that imitates the style of another', 'both', 8, 3),
('sanguine', 'Optimistic or positive about the future', 'both', 8, 3),
('soliloquy', 'The act of speaking one''s thoughts aloud when alone', 'both', 9, 3),
('somnolent', 'Sleepy or drowsy; inducing sleep', 'both', 9, 3),
('specious', 'Superficially plausible but actually wrong', 'both', 8, 3),
('trepidation', 'A feeling of fear or agitation about something', 'both', 11, 3),
('ubiquitous', 'Present, appearing, or found everywhere', 'both', 10, 3),
('unequivocal', 'Leaving no doubt; unambiguous', 'both', 11, 3),
('vacillate', 'To be indecisive; to waver between opinions', 'both', 9, 3),
('vehement', 'Showing strong and passionate feelings', 'both', 8, 3),
('vicarious', 'Experienced through the feelings of another person', 'both', 9, 3),
('voluminous', 'Occupying or containing a great deal of space', 'both', 10, 3),
('voracious', 'Wanting or devouring great quantities', 'both', 9, 3),
('fallacious', 'Based on a mistaken belief or unsound argument', 'both', 10, 3),
('fortuitous', 'Happening by accident or chance rather than design', 'both', 10, 3),
('haphazard', 'Lacking any obvious principle of organization', 'both', 9, 3),
('immutable', 'Unchanging over time or unable to be changed', 'both', 9, 3),
('convoluted', 'Extremely complex and difficult to follow', 'both', 10, 3),
('ameliorate', 'To make something bad or unsatisfactory better', 'both', 10, 4),
('audacious', 'Showing a willingness to take surprisingly bold risks', 'both', 9, 4),
('bifurcation', 'Division into two branches or parts', 'both', 11, 4),
('blandishment', 'A flattering statement used to persuade someone', 'both', 12, 4),
('brazenness', 'Bold and without shame or embarrassment', 'both', 10, 4),
('circuitous', 'Longer than the most direct way or route', 'both', 10, 4),
('concatenate', 'To link things together in a chain or series', 'both', 11, 4),
('contravene', 'To violate or act against a rule or treaty', 'both', 10, 4),
('deprecate', 'To express disapproval of something', 'both', 9, 4),
('desultory', 'Lacking a plan, purpose, or enthusiasm', 'both', 9, 4),
('dilatory', 'Slow to act or intended to cause delay', 'both', 8, 4),
('emaciated', 'Abnormally thin and weak from illness or hunger', 'both', 9, 4),
('emancipate', 'To set free from legal or social restrictions', 'both', 10, 4),
('encomium', 'A formal expression of high praise', 'both', 8, 4),
('erstwhile', 'Former; previous', 'both', 9, 4),
('exculpate', 'To prove that someone is not guilty of wrongdoing', 'both', 9, 4),
('extemporaneous', 'Spoken or done without preparation', 'both', 14, 4),
('felicitous', 'Well chosen or suited to the circumstances', 'both', 10, 4),
('harbinger', 'A person or thing that signals the approach of another', 'both', 9, 4),
('iconoclast', 'A person who attacks cherished beliefs or institutions', 'both', 10, 4),
('ignominious', 'Deserving or causing public disgrace or shame', 'both', 11, 4),
('imperturbable', 'Unable to be upset, excited, or annoyed', 'both', 13, 4),
('implacable', 'Unable to be placated or appeased', 'both', 10, 4),
('inexorable', 'Impossible to stop or prevent', 'both', 10, 4),
('inveterate', 'Having a habit or interest that is long-established', 'both', 10, 4),
('licentious', 'Not restrained by moral principles', 'both', 10, 4),
('lucubration', 'Laborious study or writing, especially at night', 'both', 11, 4),
('mendacious', 'Not telling the truth; lying', 'both', 10, 4),
('obdurate', 'Stubbornly refusing to change one''s opinion', 'both', 8, 4),
('obsequious', 'Excessively obedient or attentive to someone', 'both', 10, 4),
('parsimonious', 'Unwilling to spend money; extremely frugal', 'both', 12, 4),
('pejorative', 'Expressing contempt or disapproval', 'both', 10, 4),
('penchant', 'A strong or habitual liking for something', 'both', 8, 4),
('penurious', 'Extremely poor; poverty-stricken', 'both', 9, 4),
('perfunctory', 'Carried out with minimum effort or reflection', 'both', 11, 4),
('petulant', 'Childishly sulky or bad-tempered', 'both', 8, 4),
('garrulous', 'Excessively talkative about trivial matters', 'both', 9, 4),
('defamatory', 'Intended to damage the reputation of someone', 'both', 10, 4),
('patrician', 'A person of refined and cultivated taste', 'both', 9, 4),
('brouhaha', 'A noisy and overexcited reaction or response', 'both', 8, 4),
('disabuse', 'To persuade someone that a belief is mistaken', 'both', 8, 4);
